// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:ai_gpt/unpublish.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: webapiKey,
    appId: '1:662930862570:web:3567f4eaab9d4909464293',
    messagingSenderId: '662930862570',
    projectId: 'test-181d2',
    authDomain: 'test-181d2.firebaseapp.com',
    storageBucket: 'test-181d2.firebasestorage.app',
    measurementId: 'G-074R8QDMMH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: AndroidApiKey,
    appId: '1:662930862570:android:3ea820554412d112464293',
    messagingSenderId: '662930862570',
    projectId: 'test-181d2',
    storageBucket: 'test-181d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: iOSApiKey,
    appId: '1:662930862570:ios:dbbc1adf79612c02464293',
    messagingSenderId: '662930862570',
    projectId: 'test-181d2',
    storageBucket: 'test-181d2.firebasestorage.app',
    iosBundleId: 'com.example.aiGpt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJh62vRRIr33TPf8bVxejb5r1_SODhrRY',
    appId: '1:662930862570:ios:dbbc1adf79612c02464293',
    messagingSenderId: '662930862570',
    projectId: 'test-181d2',
    storageBucket: 'test-181d2.firebasestorage.app',
    iosBundleId: 'com.example.aiGpt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0iFhUiN-fmLktgZE7aq6QJ7jCid2fxSE',
    appId: '1:662930862570:web:cc3681ff116b2da3464293',
    messagingSenderId: '662930862570',
    projectId: 'test-181d2',
    authDomain: 'test-181d2.firebaseapp.com',
    storageBucket: 'test-181d2.firebasestorage.app',
    measurementId: 'G-Q2RSWB869W',
  );
}
